# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: GMTSAR

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  S1A_Stack_CPGF_T173_Linux:

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-22.04", "ubuntu-20.04"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install system dependencies
      run: |
        uname -a
        # prepare system
        sudo apt update
        # https://github.com/gmtsar/gmtsar/wiki/GMTSAR-Wiki-Page
        sudo apt install -y csh subversion autoconf libtiff5-dev libhdf5-dev wget
        sudo apt install -y liblapack-dev
        sudo apt install -y gfortran
        sudo apt install -y g++
        sudo apt install -y libgmt-dev
        sudo apt install -y gmt-dcw gmt-gshhg
        # gmt-gshhg-full should be installed automatically (it is required to use GMTSAR landmask)
        sudo apt install -y gmt ghostscript
        # add missed package
        sudo apt install -y make
    - name: Compile GMTSAR
      run: |
        autoconf
        ./configure --with-orbits-dir=/tmp CFLAGS='-z muldefs' LDFLAGS='-z muldefs'
        make
        make install
        # check installation
        export PATH=$PATH:/home/runner/work/gmtsar/gmtsar/bin
        echo "Start gmtsar_sharedir.csh"
        gmtsar_sharedir.csh
    - name: Cache dataset
      uses: actions/cache@v3
      with:
        path: S1A_Stack_CPGF_T173.tar.gz
        key: S1A_Stack_CPGF_T173.tar.gz
        restore-keys: S1A_Stack_CPGF_T173
    - name: Download dataset
      run: |
        wget -c http://topex.ucsd.edu/gmtsar/tar/S1A_Stack_CPGF_T173.tar.gz
        tar xvzf S1A_Stack_CPGF_T173.tar.gz -C .
    - name: Run test
      run: |
        export PATH=$PATH:/home/runner/work/gmtsar/gmtsar/bin
        ./README_prep.txt
        ./README_proc.txt
        ./README_sbas.txt

  S1A_Stack_CPGF_T173_MacOS:

    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, macos-11]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install system dependencies
      run: |
        uname -a
        # prepare system
        brew install wget libtiff hdf5 gmt ghostscript autoconf
    - name: Compile GMTSAR
      run: |
        autoconf
        ./configure --with-orbits-dir=/tmp
        make
        make install
        # check installation
        export PATH=$PATH:/Users/runner/work/gmtsar/gmtsar/bin
        echo "Start gmtsar_sharedir.csh"
        gmtsar_sharedir.csh
    - name: Cache dataset
      uses: actions/cache@v3
      with:
        path: S1A_Stack_CPGF_T173.tar.gz
        key: S1A_Stack_CPGF_T173.tar.gz
        restore-keys: S1A_Stack_CPGF_T173
    - name: Download dataset
      run: |
        wget -c http://topex.ucsd.edu/gmtsar/tar/S1A_Stack_CPGF_T173.tar.gz
        tar xvzf S1A_Stack_CPGF_T173.tar.gz -C .
    - name: Run test
      run: |
        export PATH=$PATH:/Users/runner/work/gmtsar/gmtsar/bin
        ./README_prep.txt
        ./README_proc.txt
        ./README_sbas.txt
